set dotenv-load

build:
  #!/bin/bash
  gleam build

  DIR=./build/dev/javascript/spider_extension/spider_extension
  CONTENT_FILE=$DIR/content.js
  BACKGROUND_FILE=$DIR/background.js
  CONTENT_DIST_FILE=$DIR/content.dist.js
  BACKGROUND_DIST_FILE=$DIR/background.dist.js

  echo -e "import { main } from './background.mjs' ;\nmain();" > $BACKGROUND_FILE
  echo -e "import { main } from './content.mjs' ;\nmain();" > $CONTENT_FILE

  bun build $CONTENT_FILE --outfile=$CONTENT_DIST_FILE --target browser
  bun build $BACKGROUND_FILE --outfile=$BACKGROUND_DIST_FILE --target browser

build-watch:
  watchexec \
     --restart --verbose --wrap-process=session --stop-signal SIGTERM \
     --exts gleam,js --debounce 500ms \
     --watch src/ \
     -- "just build"
