set dotenv-load

build:
  #!/bin/bash
  gleam build

  CONTENT_FILE=./build/dev/javascript/spider_extension/spider_extension/content.js
  BACKGROUND_FILE=./build/dev/javascript/spider_extension/spider_extension/background.js

  echo -e "import { main } from './background.mjs' ;\nmain();" > $BACKGROUND_FILE
  echo -e "import { main } from './content.mjs' ;\nmain();" > $CONTENT_FILE

  bun build $CONTENT_FILE --outfile=./build/dev/javascript/spider_extension/spider_extension/content.dist.js --target browser
  bun build $BACKGROUND_FILE --outfile=./build/dev/javascript/spider_extension/spider_extension/background.dist.js --target browser

build-watch:
  watchexec \
     --restart --verbose --wrap-process=session --stop-signal SIGTERM \
     --exts gleam,js --debounce 500ms \
     --watch src/ \
     -- "just build"
